# Generated by Django 2.1.1 on 2018-09-30 19:41

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180921_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Skills & Interests'),
        ),
    ]
